name: bookieslist
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  google_fonts: ^6.1.0
  percent_indicator: ^4.2.3

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  intro_slider: ^4.2.1
  sign_in_with_apple: ^5.0.0
  button_animations: ^2.0.0+3
  constants: ^0.0.1
  flutter_animate: ^4.2.0+1
  infinite_scroll_pagination: ^4.0.0
  fl_chart: ^0.64.0
  intl: ^0.18.1
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1 
  rflutter_alert: ^2.0.7
  image_picker: ^1.0.4
  email_validator: ^2.1.17
  http: ^1.1.0
  firebase_core: ^2.24.2
  flutter_barcode_scanner: ^2.0.0
  googleapis: ^12.0.0
  table_calendar: ^3.0.9
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8


flutter_native_splash:
  color: "#AC5859"
  branding: assets/images/splash.png
  branding_mode: bottom

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/splash.png
    - assets/images/scanning.png
    - assets/images/scanner-logo.png
    - assets/images/home.png
    - assets/images/avatar.png
    
    - assets/bookimages/life_after.jpg
    - assets/bookimages/das-ist-erst.jpg
    - assets/bookimages/Fourth_wings.jpg
    - assets/bookimages/Huskyküsse.jpg
    - assets/bookimages/keep-my.jpg
    - assets/bookimages/wiccacreed.jpeg
    - assets/bookimages/erwachte-magie.jpg
    - assets/bookimages/bad-at-love.jpeg
    - assets/bookimages/werbung.jpeg
    - assets/bookimages/wir-wollen.jpg
    - assets/bookimages/vampires_of_vensaya.jpeg
    - assets/bookimages/das-biest.jpeg
    - assets/bookimages/verborgene-magie.jpeg
    - assets/bookimages/bis-zum-hellsten-morgen.webp
    - assets/bookimages/fallen-princes.jpeg
    - assets/bookimages/eine-frage-der-chemie.jpeg
    - assets/bookimages/check-mate.jpg
    - assets/bookimages/queen-of-myth.webp
    - assets/bookimages/a-night-of.webp
    - assets/bookimages/easthaven.jpeg
    - assets/bookimages/what-if.jpeg
    - assets/bookimages/autumn-leaf.jpeg
    - assets/bookimages/die-drachenhexe.jpeg
    - assets/bookimages/on-my-way.jpeg
    - assets/bookimages/mister-liberty.jpeg
    - assets/bookimages/bullshit-bingo.jpeg
    - assets/bookimages/Homecoming.jpeg
    - assets/bookimages/wing-special.webp
    - assets/bookimages/ruhe-vor-dem-sturm.jpg
    - assets/bookimages/hp-all.jpeg
    - assets/bookimages/all-in.jpg
    - assets/bookimages/stadt-der-freude.jpg
    - assets/bookimages/written-in-blood.png
    - assets/bookimages/trotze-der-nacht.png
    - assets/bookimages/better-with.jpeg
    - assets/bookimages/matt-perry.jpeg
    - assets/bookimages/eine.jpeg
    - assets/bookimages/princess-and-beast.jpeg
    - assets/bookimages/miamo-zesi.webp
    - assets/bookimages/destroyed-hearts.jpeg
    - assets/bookimages/rise-doom.webp
    - assets/bookimages/rise&doom.jpeg
    - assets/bookimages/rise-doom-3.jpg
    - assets/bookimages/panem-2.jpeg
    - assets/bookimages/panem-1.jpeg
    - assets/bookimages/panem-x.jpeg
    - assets/bookimages/belle-morte.webp
    - assets/bookimages/destroyed-souls-1.jpeg
    - assets/bookimages/wiccacreed-2.jpeg
    - assets/bookimages/wish.png
  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Bold.ttf
        - asset: assets/fonts/DancingScript-Medium.ttf
        - asset: assets/fonts/DancingScript-Regular.ttf
        - asset: assets/fonts/DancingScript-SemiBold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
