name: bookieslist
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  google_fonts: ^6.1.0
  percent_indicator: ^4.2.3

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  intro_slider: ^4.2.1
  sign_in_with_apple: ^5.0.0
  button_animations: ^2.0.0+3
  constants: ^0.0.1
  flutter_animate: ^4.2.0+1
  infinite_scroll_pagination: ^4.0.0
  fl_chart: ^0.64.0
  intl: ^0.18.1
  shimmer: ^3.0.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/avatar.png
    - assets/images/life_after.jpg
    - assets/images/das-ist-erst.jpg
    - assets/images/Fourth_wings.jpg
    - assets/images/Huskyküsse.jpg
    - assets/images/keep-my.jpg
    - assets/images/wiccacreed.jpeg
    - assets/images/erwachte-magie.jpg
    - assets/images/bad-at-love.jpeg
    - assets/images/logo.png
    - assets/images/werbung.jpeg
    - assets/images/wir-wollen.jpg
    - assets/images/vampires_of_vensaya.jpeg
    - assets/images/das-biest.jpeg
    - assets/images/verborgene-magie.jpeg
    - assets/images/bis-zum-hellsten-morgen.webp
    - assets/images/fallen-princes.jpeg
    - assets/images/eine-frage-der-chemie.jpeg
    - assets/images/check-mate.jpg
    - assets/images/queen-of-myth.webp
    - assets/images/a-night-of.webp
    - assets/images/easthaven.jpeg
    - assets/images/what-if.jpeg
    - assets/images/autumn-leaf.jpeg
    - assets/images/die-drachenhexe.jpeg
    - assets/images/on-my-way.jpeg
    - assets/images/mister-liberty.jpeg
    - assets/images/bullshit-bingo.jpeg
    - assets/images/Homecoming.jpeg
    - assets/images/wing-special.webp
    - assets/images/ruhe-vor-dem-sturm.jpg
    - assets/images/hp-all.jpeg
    - assets/images/all-in.jpg
    - assets/images/stadt-der-freude.jpg
    - assets/images/written-in-blood.png
    - assets/images/trotze-der-nacht.png
    - assets/images/better-with.jpeg
    - assets/images/matt-perry.jpeg
    - assets/images/eine.jpeg
    - assets/images/princess-and-beast.jpeg
    - assets/images/miamo-zesi.webp
    - assets/images/destroyed-hearts.jpeg
    - assets/images/rise-doom.webp
    - assets/images/rise&doom.jpeg
    - assets/images/rise-doom-3.jpg
    - assets/images/panem-2.jpeg
    - assets/images/panem-1.jpeg
    - assets/images/panem-x.jpeg
    - assets/images/belle-morte.webp
    - assets/images/destroyed-souls-1.jpeg
    - assets/images/wiccacreed-2.jpeg
    - assets/images/scanning.png  
    - assets/images/scanner-logo.png 

  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Bold.ttf
        - asset: assets/fonts/DancingScript-Medium.ttf
        - asset: assets/fonts/DancingScript-Regular.ttf
        - asset: assets/fonts/DancingScript-SemiBold.ttf
    - family: Roboto
      fonts: 
        - asset: assets/fonts/Roboto-BoldItalic.ttf 
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
